#!/bin/bash
source .env
set -x
docker stop markdown-blob-server && docker rm markdown-blob-server
docker run -p 8080:8080 \
  --name markdown-blob-server \
  -e PORT=${PORT} \
  -e JWT_ACCESS_TOKEN_LIFETIME=${JWT_ACCESS_TOKEN_LIFETIME} \
  -e JWT_REFRESH_TOKEN_LIFETIME=${JWT_REFRESH_TOKEN_LIFETIME} \
  -e JWT_SECRET=${JWT_SECRET} \
  -e VERIFY_TOKEN_LIFETIME=${VERIFY_TOKEN_LIFETIME} \
  -e DB_URL=${DB_URL} \
  -e DB_USERNAME=${DB_USERNAME} \
  -e DB_PASSWORD=${DB_PASSWORD} \
  -e MAIL_HOST=${MAIL_HOST} \
  -e MAIL_USERNAME=${MAIL_USERNAME} \
  -e MAIL_PASSWORD=${MAIL_PASSWORD} \
  -e MARKDOWN_STORAGE_BUCKET_NAME=${MARKDOWN_STORAGE_BUCKET_NAME} \
  -e MARKDOWN_STORAGE_SERVICE_ENDPOINT=${MARKDOWN_STORAGE_SERVICE_ENDPOINT} \
  -e MARKDOWN_STORAGE_REGION=${MARKDOWN_STORAGE_REGION} \
  -e MARKDOWN_STORAGE_ACCESS_KEY_ID=${MARKDOWN_STORAGE_ACCESS_KEY_ID} \
  -e MARKDOWN_STORAGE_SECRET_KEY=${MARKDOWN_STORAGE_SECRET_KEY} \
  -e ENV_TYPE=${ENV_TYPE} \
  markdown-blob-server:latest