#!/bin/bash
source .env
source ./stop.sh
docker run -p 8080:8080 \
  --name markdown-blob-server \
  -e SERVER_PORT=${SERVER_PORT} \
  -e JWT_ACCESS_TOKEN_LIFETIME=${JWT_ACCESS_TOKEN_LIFETIME} \
  -e JWT_REFRESH_TOKEN_LIFETIME=${JWT_REFRESH_TOKEN_LIFETIME} \
  -e JWT_SECRET=${JWT_SECRET} \
  -e VERIFY_TOKEN_LIFETIME=${VERIFY_TOKEN_LIFETIME} \
  -e DATABASE_URL=${DATABASE_URL} \
  -e MARKDOWN_STORAGE_BUCKET_NAME=${MARKDOWN_STORAGE_BUCKET_NAME} \
  -e MARKDOWN_STORAGE_SERVICE_ENDPOINT=${MARKDOWN_STORAGE_SERVICE_ENDPOINT} \
  -e MARKDOWN_STORAGE_REGION=${MARKDOWN_STORAGE_REGION} \
  -e MARKDOWN_STORAGE_ACCESS_KEY_ID=${MARKDOWN_STORAGE_ACCESS_KEY_ID} \
  -e MARKDOWN_STORAGE_SECRET_KEY=${MARKDOWN_STORAGE_SECRET_KEY} \
  -e ENV_TYPE=${ENV_TYPE} \
  markdown-blob-server:latest
